version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.production
    command: bash -c 'sleep 3 && npm test'
    image: kirildz/devops-for-programmers-project-74
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_NAME: postgres
    restart: always
