version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.production
    command: bash -c 'sleep 3 && npm test'
    image: kirildz/devops-for-programmers-project-74:latest
    volumes:
      - ".env.example:/app/.env"
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_HOST}
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
