version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.production
    command: npm test
#    volumes:
#      - ./app:/app
    image: kirildz/devops-for-programmers-project-74
